<script src="<?php echo base_url(); ?>assets/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxdata.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxmenu.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxcheckbox.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxlistbox.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxdropdownlist.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.filter.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxcalendar.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxdatetimeinput.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxdata.export.js"></script> 
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.export.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.sort.js"></script> 
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.pager.js"></script> 
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.selection.js"></script> 
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.edit.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.grouping.js"></script>
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxgrid.aggregates.js"></script> 
<script type="text/javascript" src="<?php echo base_url(); ?>assets/jqwidgets/jqxnumberinput.js"></script> 